### ISSUE TITLE
Context in BaseObservable

### ISSUE THREAD

**Issue by eugenio1590** [etiennelenhart/Eiffel#125]
Hi @etiennelenhart after a long time I continue using this library. I know that you have introduced new changes, but speaking of version 4.1.0, how can I get the reference to the context within a BindingState? This is an example:

````
class CatBindingState : BaseObservable(), BindingState<CatViewState> {

  override fun refresh(state: CatViewState) {
      context.getString() ......
  }

}
````

**Comment by etiennelenhart** [comment]
Hey @eugenio1590, thanks for your question.

Since the `BindingState` is part of an `Activity` or `Fragment` you should, in theory, be fine with injecting a `Context` in the state's constructor.

That being said, it's probably easier and safer to not depend on a `Context` in your `BindingState`.
Have a look at the [BindingState section](https://github.com/etiennelenhart/Eiffel/blob/master/README.md#bindingstate) in the Readme.
You basically simply provide the resource IDs instead of the actual resolved resources:
```kotlin
class AngryCatBindingState : BindingState<AngryCatViewState> {
    val soundResId = ObservableInt(0)
    val catResId = ObservableInt(R.drawable.cat)

    override fun refresh(state: AngryCatViewState) {
        soundResId.set(if (state.meowing) R.string.meow else 0)
        catResId.set(if (state.meowing) R.drawable.angry_cat else R.drawable.cat)
    }
}
```
These IDs are perfectly usable in your layout using Data Binding:
```xml
<layout ...>

        <data>
            <variable
                name="viewmodel"
                type="com.fluffycat.friendlymittens.angrycat.viewmodel.AngryCatViewModel"/>

            <variable
                name="state"
                type="com.fluffycat.friendlymittens.angrycat.state.AngryCatBindingState"/>
        </data>

        ...

            <ImageView
                ...
                app:imageResource="@{state.catResId}"/>

            <TextView
                ...
                android:text="@{state.soundResId}"/>

        ...

</layout>
```

Hope this answers your question. 🙂

**Comment by eugenio1590** [comment]
Hi @etiennelenhart I see. I can try to add a context in the constructor of the class. I need to get a string but with parameters, so I need the context to do it. Thanks for your help.

**Comment by etiennelenhart** [comment]
Ah, in that case note, that there also is a context available in Binding expressions:
```xml
android:text='@{context.getString(id)}"
```
So you should be able to combine both approaches without the need for injecting a context.

**Comment by eugenio1590** [comment]
Yes, I considered that implementation using the context in the binding but the logic is complicated. Using the context in the constructor of the BindingState is worked for me. Thanks.
