### ISSUE TITLE
Decrease unnecessary minSdkVersion 19 to 14

### ISSUE THREAD

**Issue by alirezara** [etiennelenhart/Eiffel#39]
Hi! 
My question is why minimum SDK value is 19 while minimum SDK of android architecture components is 14?

**Comment by etiennelenhart** [comment]
Hey, thanks for the good question. I honestly just picked it since that's what I use for new app projects. Sometimes even 21, since here in Europe the percentage of devices actually using 19 or below is basically non-existent.

But I see no problem in decreasing it to 14 if you'd like to use it in projects that require a low minSdk.

**Comment by alirezara** [comment]
Thank's for the answer my friend.
