### ISSUE TITLE
Demo App

### ISSUE THREAD

**Issue by jordond** [etiennelenhart/Eiffel#54]
I was wondering if you had a demo app that utilizes this library.

I am currently working on something similar to this on my own project, and would love to not have to write something myself.  Having a demo app would be nice so that I wouldn't have to take the time to do it myself.

**Comment by etiennelenhart** [comment]
Hey, thanks for the question.

Not at the moment. With a full time job and a baby at home I'm unfortunately a bit short on time. I'm currently planning to shift Eiffel's architecture to a more Redux like approach (see #50) and would really like to also provide a demo app for this. It just might take a while.

I'm not sure whether the updated approach will fit your own project, but I feel like it will take the library to the next level and the core principles will still apply.

It would be helpful if you could maybe propose the kind of demo app you would like to see. Like what types of screens, navigation, UI components and service interactions.

I'd still schedule this for after 5.0.0 though, since I currently just don't have enough time.

**Comment by jordond** [comment]
No worries!  It's just helpful for libraries to have demo apps, to show off some basic implementation.

Once 5.0.0 is out I can even take a stab at creating a sample app.
